package openai_mock_server

//go:generate go tool logcopter-gen -include-main -var zlog -area-prefix go-go-golems.openai-mock-server -strip-prefix github.com/go-go-golems/openai-mock-server ./cmd/... ./pkg/...
