// Code generated by logcopter-gen; DO NOT EDIT.

package config

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.openai-mock-server.pkg.server.config")
